### PR TITLE
External color mode

### LINKED ISSUE #13: Different colors for different External elements
This should be a *mode* that can be activated on demand (initially, only one color should be used for all external elements, as it is now) - also see http://vowl.visualdataweb.org/v2/#externalElements

Each base URI is mapped to one of the colors. 

We should first try a generic approach: https://github.com/mbostock/d3/wiki/Ordinal-Scales#colorbrewer

If this does not lead to a good result, we can use the color palette of 10 distinct colors provided by D3 (current external color can be replaced by the first color of the color palette, i.e., by #1f77b4): https://github.com/mbostock/d3/wiki/Ordinal-Scales#category10

We could also try a mixed approach, i.e., use the well-designed color palette for the first 10 colors and switch to the generic approach for colors 11 to n - or, alternatively, use directly the generic approach if there are more than 10 base URIs (and the color palette if there are less).

Let's try and see what looks and scales best.

### TODO
- [x] Handle greater base iri count than there are colors
- [x] Pass baseIRI from OWL2VOWL to WebVOWL

### PR DESCRIPTION
**Pull request by linkvt**
Closes #13 

[webvowl-external-mode-c08aa31.zip](https://github.com/VisualDataWeb/WebVOWL/files/139591/webvowl-external-mode-c08aa31.zip)

### CODE REVIEW

**Comment by steffen-l** [comment]
Looks good. Let's rename the mode into "Color externals" in the menu, resolve the conflicts, and merge the new feature. It is really hard to find better colors (most basic colors are already used in VOWL), so let's keep these colors for now.

**Comment by linkvt** [comment]
Resolved conflicts

**Comment by steffen-l** [comment]
Cursor doesn't turn into hand icon on the items of the menus gravity, filter, and mode. It turns correctly for the ontology, export and about menus. Bug appears in both Firefox and Chrome.

**Comment by steffen-l** [comment]
I see. This is not wanted to check boxes and sliders. Fine for me.

**Pull request merged**
