### PR TITLE
Moving Grunt tasks to Webpack 2

### PR DESCRIPTION
**Pull request by leshek-pawlak**
Hi guys,

Thanks for developing this project.
I'm using it and I think is really great.
This time I want to share my work with the others.
I rewrote all grunt tasks to webpack. 
For my needs, it's working well, but please check if every task you need is included to webpack.

I hope it will help be more productive all developers contributing the WebVOWL.
By the way, I've added PostCSS Autoprefixer for CSSs and updated webpack to 2 version.

Cheers,
Leszek

### CODE REVIEW

**Comment by leshek-pawlak** [comment]
https://github.com/VisualDataWeb/WebVOWL/issues/85

**Comment by linkvt** [comment]
Hi,
thank you for this PR, after taking a quick look over it, it seems interesting and I could learn something from it.
Since I'm currently not an active maintainer somebody else should approve this PR when its finished/accepted.

I noticed a few things that should be adjusted if the switch to webpack is accepted:
- [ ] the travis build is failing because `grunt` is still called in [.travis.yml#L10](https://github.com/VisualDataWeb/WebVOWL/blob/master/.travis.yml#L10) to execute `jshint`
- [ ] the bump plugin now has a different feature set, the `grunt` plugin has a lot more capabilities - but idk if they are still used: https://github.com/vojtajina/grunt-bump#usage-examples
- [ ] the README still contains instructions for `grunt`

I really like the addition of autoprefixer for a better compatibility and it might allow to tidy the current CSS a bit.

Thanks

**Comment by leshek-pawlak** [comment]
Hi @linkvt,

Thanks for your message. 
I'm glad that you think it's interesting. :)
I'll fix the travis bug and I'll change a little bit README file - they're simple things.

Now I see what's doing this "grunt-bump" plugin. 
I'll try to find webpack solution for that.

**Comment by leshek-pawlak** [comment]
I did some research in the "bumping" tools for webpack and CLI. 
I think that grunt-bump is the best solution nowadays. 
There is no reason to change it to another tool.

Please check again if my changes are acceptable for you.

**Comment by linkvt** [comment]
Thanks for your changes, I really appreciate it.
I still have to refer to the [comment of Steffen](https://github.com/VisualDataWeb/WebVOWL/issues/85#issuecomment-295794619) that he will consider it with the current maintainer, since I'm not actively involved in the development process anymore - so I can't decide if this PR will be accepted.

**Pull request closed without merging**
